```powershell
#Requires -Version 7.0

$ErrorActionPreference = "Stop"

# ============================================================
# MJCC FLUTTER APK BUILDER
#
# Flow:
#   1. Start Laravel serve-public.ps1
#   2. Wait for Cloudflare Tunnel URL
#   3. Detect https://xxxxx.trycloudflare.com
#   4. Pass URL to Flutter using --dart-define
#   5. Build release APK
#
# Flutter AppConfig:
#   API_BASE_URL -> https://xxxxx.trycloudflare.com
#   API prefix  -> /api/v1
#
# ============================================================


# ============================================================
# CONFIGURATION
# ============================================================

# This script is located inside:
# D:\mjccMain\apk\mjcc
$FlutterDir = $PSScriptRoot

# Laravel project:
# D:\mjccMain\mjcc
$LaravelDir = "D:\mjccMain\mjcc"

# Existing Laravel public/tunnel script
$ServeScript = Join-Path $LaravelDir "serve-public.ps1"

# Directory used by serve-public.ps1
$TunnelDir = Join-Path $env:TEMP "mjcc-serve-public"

# Logs generated by serve-public.ps1
$TunnelLog = Join-Path $TunnelDir "tunnel.log"
$TunnelErrorLog = Join-Path $TunnelDir "tunnel.err.log"

# Flutter generated APK
$ApkPath = Join-Path `
    $FlutterDir `
    "build\app\outputs\flutter-apk\app-release.apk"


# ============================================================
# FUNCTIONS
# ============================================================

function Write-Step {
    param(
        [string]$Message
    )

    Write-Host ""
    Write-Host "------------------------------------------------------------" `
        -ForegroundColor DarkGray

    Write-Host $Message -ForegroundColor Yellow

    Write-Host "------------------------------------------------------------" `
        -ForegroundColor DarkGray
}


function Get-CloudflareUrl {

    $timeoutSeconds = 90
    $startTime = Get-Date

    while (((Get-Date) - $startTime).TotalSeconds -lt $timeoutSeconds) {

        Start-Sleep -Milliseconds 750

        $logFiles = @(
            $TunnelLog,
            $TunnelErrorLog
        ) | Where-Object {
            Test-Path $_
        }

        if ($logFiles.Count -eq 0) {
            continue
        }

        $matches = Select-String `
            -Path $logFiles `
            -Pattern 'https://[a-zA-Z0-9-]+\.trycloudflare\.com' `
            -AllMatches `
            -ErrorAction SilentlyContinue

        if ($matches) {

            foreach ($match in $matches) {

                foreach ($urlMatch in $match.Matches) {

                    $url = $urlMatch.Value.Trim()

                    if ($url -match '^https://[a-zA-Z0-9-]+\.trycloudflare\.com$') {
                        return $url
                    }
                }
            }
        }
    }

    return $null
}


# ============================================================
# HEADER
# ============================================================

Clear-Host

Write-Host ""
Write-Host "============================================================" `
    -ForegroundColor Cyan

Write-Host "          MJCC FLUTTER APK BUILDER" `
    -ForegroundColor Cyan

Write-Host "============================================================" `
    -ForegroundColor Cyan

Write-Host ""

Write-Host "Flutter project:"
Write-Host $FlutterDir -ForegroundColor White

Write-Host ""

Write-Host "Laravel project:"
Write-Host $LaravelDir -ForegroundColor White

Write-Host ""


# ============================================================
# CHECK FLUTTER
# ============================================================

Write-Step "[1/6] Checking Flutter installation..."

if (-not (Get-Command flutter -ErrorAction SilentlyContinue)) {

    Write-Host ""
    Write-Host "ERROR: Flutter was not found in PATH." `
        -ForegroundColor Red

    Write-Host ""
    Write-Host "Try:"
    Write-Host "flutter --version"

    exit 1
}

Write-Host ""
Write-Host "Flutter found." -ForegroundColor Green

flutter --version


# ============================================================
# CHECK LARAVEL SCRIPT
# ============================================================

Write-Step "[2/6] Checking Laravel serve-public.ps1..."

if (-not (Test-Path $LaravelDir)) {

    Write-Host ""
    Write-Host "ERROR: Laravel directory does not exist:" `
        -ForegroundColor Red

    Write-Host $LaravelDir

    exit 1
}

if (-not (Test-Path $ServeScript)) {

    Write-Host ""
    Write-Host "ERROR: serve-public.ps1 was not found:" `
        -ForegroundColor Red

    Write-Host $ServeScript

    exit 1
}

Write-Host ""
Write-Host "serve-public.ps1 found." -ForegroundColor Green


# ============================================================
# PREPARE TUNNEL LOG DIRECTORY
# ============================================================

Write-Step "Preparing Cloudflare tunnel logs..."

New-Item `
    -ItemType Directory `
    -Path $TunnelDir `
    -Force `
    | Out-Null

# IMPORTANT:
# Delete old logs so we don't accidentally use
# an old Cloudflare URL.

Remove-Item `
    $TunnelLog `
    -Force `
    -ErrorAction SilentlyContinue

Remove-Item `
    $TunnelErrorLog `
    -Force `
    -ErrorAction SilentlyContinue

Write-Host ""
Write-Host "Old tunnel logs removed." -ForegroundColor Green


# ============================================================
# START SERVE-PUBLIC.PS1
# ============================================================

Write-Step "[3/6] Starting Laravel + Cloudflare Tunnel..."

Write-Host ""
Write-Host "Starting:"
Write-Host $ServeScript -ForegroundColor Cyan
Write-Host ""

$ServeProcess = Start-Process `
    -FilePath "pwsh.exe" `
    -ArgumentList @(
        "-NoProfile",
        "-ExecutionPolicy",
        "Bypass",
        "-File",
        "`"$ServeScript`""
    ) `
    -WorkingDirectory $LaravelDir `
    -PassThru

Write-Host ""
Write-Host "serve-public.ps1 started." -ForegroundColor Green
Write-Host "Process ID: $($ServeProcess.Id)" -ForegroundColor DarkGray


# ============================================================
# WAIT FOR CLOUDFLARE URL
# ============================================================

Write-Step "[4/6] Waiting for Cloudflare public URL..."

Write-Host ""
Write-Host "Waiting up to 90 seconds..." -ForegroundColor DarkGray

$PublicUrl = Get-CloudflareUrl

if (-not $PublicUrl) {

    Write-Host ""
    Write-Host "============================================================" `
        -ForegroundColor Red

    Write-Host "       ERROR: CLOUDFLARE URL NOT FOUND" `
        -ForegroundColor Red

    Write-Host "============================================================" `
        -ForegroundColor Red

    Write-Host ""

    if (Test-Path $TunnelLog) {

        Write-Host "Tunnel output:" `
            -ForegroundColor Yellow

        Write-Host ""

        Get-Content `
            $TunnelLog `
            -Tail 50
    }

    if (Test-Path $TunnelErrorLog) {

        Write-Host ""
        Write-Host "Tunnel errors:" `
            -ForegroundColor Yellow

        Write-Host ""

        Get-Content `
            $TunnelErrorLog `
            -Tail 50
    }

    Write-Host ""

    exit 1
}


# ============================================================
# DISPLAY CLOUDFLARE URL
# ============================================================

Write-Host ""
Write-Host "============================================================" `
    -ForegroundColor Green

Write-Host "       CLOUDFLARE PUBLIC URL FOUND" `
    -ForegroundColor Green

Write-Host "============================================================" `
    -ForegroundColor Green

Write-Host ""

Write-Host "Public URL:" `
    -ForegroundColor Cyan

Write-Host $PublicUrl `
    -ForegroundColor Green

Write-Host ""

Write-Host "Flutter API URL:" `
    -ForegroundColor Cyan

Write-Host "$PublicUrl/api/v1" `
    -ForegroundColor Green

Write-Host ""


# ============================================================
# MOVE TO FLUTTER PROJECT
# ============================================================

Set-Location $FlutterDir


# ============================================================
# FLUTTER CLEAN
# ============================================================

Write-Step "[5/6] Preparing Flutter project..."

Write-Host ""
Write-Host "Running flutter clean..." -ForegroundColor Cyan

flutter clean

if ($LASTEXITCODE -ne 0) {

    Write-Host ""
    Write-Host "ERROR: flutter clean failed." `
        -ForegroundColor Red

    exit 1
}


# ============================================================
# FLUTTER PUB GET
# ============================================================

Write-Host ""
Write-Host "Running flutter pub get..." -ForegroundColor Cyan

flutter pub get

if ($LASTEXITCODE -ne 0) {

    Write-Host ""
    Write-Host "ERROR: flutter pub get failed." `
        -ForegroundColor Red

    exit 1
}


# ============================================================
# BUILD APK
# ============================================================

Write-Step "[6/6] Building release APK..."

Write-Host ""
Write-Host "IMPORTANT:"
Write-Host "The following URL will be embedded into this APK:"
Write-Host ""
Write-Host "$PublicUrl" -ForegroundColor Green
Write-Host ""

Write-Host "Flutter will receive:"
Write-Host ""
Write-Host "--dart-define=API_BASE_URL=$PublicUrl" `
    -ForegroundColor Cyan

Write-Host ""

flutter build apk --release `
    "--dart-define=API_BASE_URL=$PublicUrl"

if ($LASTEXITCODE -ne 0) {

    Write-Host ""
    Write-Host "============================================================" `
        -ForegroundColor Red

    Write-Host "              APK BUILD FAILED" `
        -ForegroundColor Red

    Write-Host "============================================================" `
        -ForegroundColor Red

    exit 1
}


# ============================================================
# CHECK APK
# ============================================================

if (-not (Test-Path $ApkPath)) {

    Write-Host ""
    Write-Host "ERROR: Flutter reported success but APK was not found:" `
        -ForegroundColor Red

    Write-Host $ApkPath

    exit 1
}


$Apk = Get-Item $ApkPath

$ApkSizeMB = [math]::Round(
    $Apk.Length / 1MB,
    2
)


# ============================================================
# SUCCESS
# ============================================================

Write-Host ""
Write-Host ""
Write-Host "============================================================" `
    -ForegroundColor Green

Write-Host "                 APK BUILD SUCCESS" `
    -ForegroundColor Green

Write-Host "============================================================" `
    -ForegroundColor Green

Write-Host ""

Write-Host "Laravel / Cloudflare URL:" `
    -ForegroundColor Cyan

Write-Host $PublicUrl `
    -ForegroundColor Green

Write-Host ""

Write-Host "Flutter API URL:" `
    -ForegroundColor Cyan

Write-Host "$PublicUrl/api/v1" `
    -ForegroundColor Green

Write-Host ""

Write-Host "APK file:" `
    -ForegroundColor Cyan

Write-Host $Apk.FullName `
    -ForegroundColor Green

Write-Host ""

Write-Host "APK size:" `
    -ForegroundColor Cyan

Write-Host "$ApkSizeMB MB" `
    -ForegroundColor White

Write-Host ""

Write-Host "============================================================" `
    -ForegroundColor Green

Write-Host ""

Write-Host "Keep serve-public.ps1 running while testing this APK." `
    -ForegroundColor Yellow

Write-Host ""

# Open Windows Explorer and select the APK
Start-Process explorer.exe `
    -ArgumentList "/select,`"$($Apk.FullName)`""

Write-Host "Done." -ForegroundColor Green

